### ISSUE TITLE
Вор и рыцарь

### ISSUE THREAD

**Issue by OldHuntsman** [OldHuntsman/DefilerWings#50]
Переписал диздок, но чтобы там не выискивать суммирую сюда. Что надо изменить по вору и рыцарю.
1) Шанс появления. Теперь предполагаем следующую схему: 
Существует 5 шансов что вор НЕ появится. Каждый уровень дурной славы добавляет 1 шанс что появится. Соотвественно при 1 уровне ДС шанс на появление 1 из 6, при втором 2 из 7 и т.д.
Потом определяем уровень его мастерства, по старой схеме: три шанса +1 шанс за каждый уровень дурной славы дракона. Каждый шанс 1 из 3 что уровень вора увеличится на 1 (начиная с 0). Если уровень вора вышел нулевым, о в этом году вор всё ещё не появляется.
Рыцарю теперь даём только ОДНУ способность, и делается на неё ОДНА проверка.
2) Шансы получения особых предметов за квесты, снижаем с 50% до 30%
3) Рыцарь сейчас очень уж ВНЕЗАПНЫЙ. Сразу начинает бой. Надо так: сначала даём текст <титул-имя рыцарь> нашел логово где спит <полное имя дракона> и вызывает его на бой. Потом цитата от рыцаря типа: "Выходи подлый <тип дракона> на честной бой, на побраночку!!!". Потом описание из боевого списка "рыцарь готовится" и под ним уровень опасности боя. Нужна возможность убежать и бросить логово даже не вступая в бой. И! Если дракон убегает от рыцаря, рыцаря не обнуляем сразу, с шансом 75% он продолжает охоту выдавая фразу: "Я всё равно тебя найду", а с 25% шансом обнуляется с фразой "Ты подлый трус <титул-имя рыцарь>, такой враг меня не достоин".
4) Вору очень нужна та самая система о которой я писал раньше. Нужно чтобы был виден КАЖДЫЙ этап его проникновения в логово. Тексты я готов написать но нужен механизм под них.

Идею с выдачей ворам и рыцарей проклятых шмоток мы заворачиваем - не хочется возиться с этим.
Про тексты. Мы сможем сделать такую механику, чтобы цитаты рыцаря/вора на старте и при заходе в логово зависели от их особенностей и уровня? Например у нас есть межевой рыцарь с особенностью "освободитель", значит у него есть шанс сказать: "Эгей я межевой рыцарь" или "Эгей на меня смотрят тёлки!". Так же хотелось бы привязать разные цитаты к разным итогам квестов, и сделать описания провальных квестов (опять же описания я наколбашу, но нужна под них рабочая схема).

**Comment by OldHuntsman** [comment]
Да, ещё момент упустил. Нужна опция просмотра текущего состояния рыцаря и вора. Делаем так:
Заходим в логово контрабандистов и платим 10 фартингов за опцию "Разузнать о воре". Нам выдаётся описание: имя и титул вора, сколько лет назад появился, какие особенности и снаряжение.
Аналогично "Разузнать о рыцаре".

Для описаний нужна возможность выдавать их художественно. Тексты я напишу когда будет куда.

**Comment by OldHuntsman** [comment]
есть еще бага такая что если у тебя в логове беременная девушка и в этот момент нападает рыцарь, убегая от него. Девушка рожает и создание приходит к дракону и спрашивает о назначении, если его назначить охранником, логово сохранится за драконом.

**Comment by HikkeKun** [comment]
>есть еще бага такая что если у тебя в логове беременная девушка и в этот момент нападает рыцарь, убегая от него. Девушка рожает и создание приходит к дракону и спрашивает о назначении, если его назначить охранником, логово сохранится за драконом.
Не, тут не так. Во всяком случае у меня так не получилось.

Сначала девушка рожает. Потом приходит рыцарь. И потом уже спрашивают что делать с тварями.
Тут надо либо чтобы рожала после рыцаря (не родит потому что логово просрано). Либо решать что делать с тварями до пробуждения (во сне О.о?). Либо вместе с девками из старого логова выгодять тварей (в никуда? слугами в новом логове, бесчинствовать в королевстве, их порежет рыцарь и нужен на это дело ивент?)

Остальное вроде сделал. Можно закрывать?
