### ISSUE TITLE
Исправить чтобы у рыцаря не выдавались в список модификаторов значения как они в коде прописаны, типа def_up

### ISSUE THREAD

**Issue by asfdfdfd** [OldHuntsman/DefilerWings#64]

**Comment by HikkeKun** [comment]
А как должны? И где выдаются в данный момент?

**Comment by asfdfdfd** [comment]
Здесь нужен комментарий @OldHuntsman , этот баг нашёл он, я сам не сталкивался (или не обратил внимания).
